# https://yunohost.org/en/packaging_config_panels
# https://github.com/YunoHost/example_ynh/blob/master/config_panel.toml.example

version = "1.0"

[main]
name.en = "Main configuration"
name.fr = "Configuration principale"
services = ["__APP__"]

    [main.config]
    name = "Configuration Options"

        [main.config.default_from_email]
        ask = "from email"
        type = "email"
        help = "Default email address to use for various automated emails."
        #
        # We can't use "__DATA_DIR__" in bind value, because of this bug:
        # https://github.com/YunoHost/issues/issues/2283
        bind = "default_from_email:/home/yunohost.app/__APP__/settings.py"

        [main.config.admin_email]
        ask = "ADMIN email"
        type = "email"
        help = "EMail address for error emails."
        bind = "admin_email:/home/yunohost.app/__APP__/settings.py"

        [main.config.debug_enabled]
        ask = "DEBUG mode"
        type = "boolean"
        yes = "1"
        no = "0"
        help = "Should be never enabled in production!"
        bind = "debug_enabled:/home/yunohost.app/__APP__/settings.py"

        [main.config.log_level]
        type = "string"
        ask = "Log Level"
        choices = ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"]
        default = "WARNING"
        bind = "log_level:/home/yunohost.app/__APP__/settings.py"

        [main.config.fritz_username]
        ask = "FRITZ USERNAME"
        type = "string"
        help = "Connection user name for your FritzBox"
        default = ""
        optional = true
        bind = "fritz_username:/home/yunohost.app/__APP__/settings.py"

        [main.config.fritz_password]
        ask = "FRITZ PASSWORD"
        type = "string"
        help = "Connection user password for your FritzBox"
        default = ""
        optional = true
        bind = "fritz_password:/home/yunohost.app/__APP__/settings.py"
